"""
Report Generator
Outputs: terminal summary, JSON, CSV, SARIF 2.1.0, PDF
"""

import json
import csv
import os
import re
import sys
from datetime import datetime

import colors as C
from payloads.atlas import ATLAS_TECHNIQUES

# ── Emoji badge support ───────────────────────────────────────────────────────
_EMOJI = False

_VERDICT_EMOJI  = {"PASS": "✅", "FAIL": "❌", "WARN": "⚠️",  "ERROR": "⚫"}
_SEVERITY_EMOJI = {"Critical": "🔴", "High": "🟠", "Medium": "🟡", "Low": "🟢"}

_ATLAS_REMEDIATION = {
    "AML.T0051": "Harden system-prompt boundaries and apply input sanitisation to prevent user-supplied text from overriding operator instructions.",
    "AML.T0057": "Strengthen refusal training and add a content-policy layer that detects persona-injection and roleplay jailbreak patterns.",
    "AML.T0027": "Deploy Unicode normalisation and adversarial-input filters before the model receives user text.",
    "AML.T0054": "Treat all retrieved external content as untrusted; strip instruction-like patterns before injecting into the context.",
    "AML.T0024": "Implement output scanning to detect and redact system-prompt leakage, PII, and training-data fragments.",
    "AML.T0056": "Restrict system-prompt disclosure via output classifiers and apply strict separation between operator and user context.",
    "AML.T0029": "Enforce per-user token and request-rate limits; return 429 before context exhaustion occurs.",
    "AML.T0034": "Set hard per-session and daily token-spend caps and alert on anomalous consumption patterns.",
    "AML.T0047": "Expand safety fine-tuning coverage for CBRN, hate-speech, and self-harm categories and add a post-generation classifier.",
    "AML.T0031": "Audit the model for evasion-based accuracy degradation and add adversarial robustness evaluations to your CI pipeline.",
    "AML.T0043": "Apply input normalisation (Unicode, encoding, obfuscation) and red-team with adversarial perturbation tools.",
    "AML.T0055": "Validate and sandbox all plugin/tool integrations; enforce least-privilege for tool-call permissions.",
    "AML.T0000": "Restrict API discoverability; avoid exposing model version, architecture, or error details in responses.",
    "AML.T0025": "Limit the precision of model outputs and add noise to prevent training-data reconstruction via repeated queries.",
}


def init_reporter(use_emoji: bool = False) -> None:
    global _EMOJI
    _EMOJI = use_emoji and sys.stdout.isatty()


def verdict_color(verdict: str) -> str:
    prefix = (_VERDICT_EMOJI.get(verdict, "") + " ") if _EMOJI else ""
    return {
        "PASS":  C.GREEN(prefix + verdict),
        "FAIL":  C.RED(prefix + verdict),
        "WARN":  C.YELLOW(prefix + verdict),
        "ERROR": C.DIM(prefix + verdict),
    }.get(verdict, verdict)


def severity_color(severity: str) -> str:
    prefix = (_SEVERITY_EMOJI.get(severity, "") + " ") if _EMOJI else ""
    return {
        "Critical": C.RED(prefix + severity),
        "High":     C.MAGENTA(prefix + severity),
        "Medium":   C.YELLOW(prefix + severity),
        "Low":      C.DIM(prefix + severity),
    }.get(severity, prefix + severity)


# ── Anonymization ────────────────────────────────────────────────────────────
_ANON_WATERMARK = "[ANONYMIZED REPORT — generated by CRUCIBLE]"


def _pdf_escape(text) -> str:
    """Escape &, <, > for reportlab Paragraph markup. Red-team payloads routinely
    contain '<', '>' and '&' (HTML/markdown injection, template payloads), which
    otherwise make reportlab's mini-XML parser raise and crash --pdf export."""
    return (str(text)
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;"))


def redact_model(model: str) -> str:
    """
    Map a specific model identifier to its anonymized model-family string.
    Examples:
        llama-3.3-70b-versatile  →  Llama (70B)
        gpt-4o                   →  GPT-4 family
        claude-sonnet-4-6        →  Claude Sonnet family
        gemma4                   →  Gemma 4 family
        openai/gpt-oss-120b      →  GPT-OSS family
    """
    m  = (model or "").strip()
    lo = m.lower()

    # Strip provider prefix (e.g. "openai/gpt-oss-120b" → "gpt-oss-120b")
    if "/" in lo:
        prefix, _, lo_short = lo.partition("/")
    else:
        prefix, lo_short = "", lo

    # ── Llama ──────────────────────────────────────────────────────────────
    if "llama" in lo_short or "llama" in prefix:
        sz = re.search(r'(\d+)\s*b', lo_short, re.IGNORECASE)
        return f"Llama ({sz.group(1).upper()}B)" if sz else "Llama family"

    # ── GPT ────────────────────────────────────────────────────────────────
    if lo_short.startswith("gpt-oss"):
        return "GPT-OSS family"
    if lo_short.startswith("gpt-4"):
        return "GPT-4 family"
    if lo_short.startswith("gpt-3"):
        return "GPT-3 family"
    if lo_short.startswith("gpt"):
        return "GPT family"

    # ── Claude ─────────────────────────────────────────────────────────────
    if lo_short.startswith("claude") or prefix == "anthropic":
        if "opus"   in lo_short: return "Claude Opus family"
        if "sonnet" in lo_short: return "Claude Sonnet family"
        if "haiku"  in lo_short: return "Claude Haiku family"
        return "Claude family"

    # ── Gemma ──────────────────────────────────────────────────────────────
    if lo_short.startswith("gemma"):
        num = re.search(r'(\d+)', lo_short)
        return f"Gemma {num.group(1)} family" if num else "Gemma family"

    # ── Gemini ─────────────────────────────────────────────────────────────
    if lo_short.startswith("gemini"):
        return "Gemini family"

    # ── Mistral / Mixtral / Codestral ──────────────────────────────────────
    if any(lo_short.startswith(x) for x in ("mistral", "mixtral", "codestral")):
        return "Mistral family"

    # ── Cohere ─────────────────────────────────────────────────────────────
    if lo_short.startswith("command"):
        return "Cohere family"

    # ── DeepSeek ───────────────────────────────────────────────────────────
    if lo_short.startswith("deepseek"):
        return "DeepSeek family"

    # ── Qwen ───────────────────────────────────────────────────────────────
    if lo_short.startswith("qwen"):
        return "Qwen family"

    # ── Fallback: first word segment, title-cased ───────────────────────────
    first = re.split(r'[-_\d]', lo_short)[0]
    return f"{first.title()} family" if first else "Unknown family"


def anonymize_config(config: dict) -> dict:
    """Return a shallow copy of *config* with credentials and endpoint redacted."""
    return {
        **config,
        "api_key":  "[REDACTED]",
        "endpoint": "[ENDPOINT REDACTED]",
        "model":    redact_model(config.get("model", "")),
    }


# PII / secret scrubbing for saved bodies (the model-stealing engine actively
# elicits secrets/PII; --anonymize must not leave them verbatim in a shared report).
_PII_SCRUB = {
    "[email]":  re.compile(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}"),
    "[ssn]":    re.compile(r"\b\d{3}-\d{2}-\d{4}\b"),
    "[secret]": re.compile(r"\b(?:sk|pk|api|key|token|AKIA)[-_A-Za-z0-9]{12,}\b", re.I),
    "[phone]":  re.compile(r"\b(?:\+?\d[\s-]?){9,}\d\b"),
}


def scrub_pii(text: str) -> str:
    """Replace emails / SSNs / API-key-like secrets / phone numbers with typed
    placeholders. Applied to saved response + payload bodies when --anonymize is set."""
    out = text or ""
    for placeholder, pat in _PII_SCRUB.items():
        out = pat.sub(placeholder, out)
    return out


def _scrub(text, anonymize: bool):
    return scrub_pii(text) if anonymize else text


# ── Token estimate ────────────────────────────────────────────────────────────
def _token_estimate(results: list) -> int:
    """Rough token count: words × 1.3 for payloads + responses."""
    total = 0
    for r in results:
        payload  = r["test"].get("payload", "")
        response = r["result"].get("response_text", "") or ""
        total += int(len(payload.split())  * 1.3)
        total += int(len(response.split()) * 1.3)
    return total


# ── Live compact one-liner (printed during run) ───────────────────────────────
def print_live_result(test: dict, result: dict, index: int, total: int):
    verdict  = result.get("verdict", "ERROR")
    progress = f"[{index:>3}/{total}]"
    print(
        f"  {C.DIM(progress)} {verdict_color(verdict):<20} "
        f"{C.CYAN(test['id']):<12} {severity_color(test.get('severity','Low')):<12} "
        f"{test['name']}"
    )


# ── Full per-test detail block ────────────────────────────────────────────────
_TERM_RESP_CAP = 500   # terminal response cap (chars)
_SEP = "─" * 68

def print_detailed_test(test: dict, result: dict) -> None:
    """
    Print the full structured detail block for a single test.
    Used during --detailed live run and in the final report sections.
    """
    verdict    = result.get("verdict", "ERROR")
    vcol       = {"PASS": C.GREEN, "FAIL": C.RED, "WARN": C.YELLOW, "ERROR": C.DIM}.get(verdict, str)
    sev        = test.get("severity", "Low")
    atlas_id   = test.get("atlas_id", "N/A") or "N/A"
    atlas_name = test.get("atlas_name", "")
    owasp_id   = test.get("owasp_id",  "N/A") or "N/A"
    signals      = result.get("signals", [])
    payload      = test.get("payload", "")
    response     = result.get("response_text", "") or ""
    judge_used   = result.get("judge_used", False)
    judge_marker = "(J)" if judge_used else ""

    verdict_badge   = (_VERDICT_EMOJI.get(verdict, "") + " ") if _EMOJI else ""
    verdict_display = verdict_badge + verdict + judge_marker

    print(f"\n  {_SEP}")
    # Header line
    print(f"  {C.CYAN(C.BOLD(test['id']))}  {C.BOLD(test['name'])}  │  "
          f"{severity_color(sev)}  │  {vcol(verdict_display)}")

    # ATLAS / OWASP tags
    tags_parts = []
    if atlas_id != "N/A":
        tag = f"ATLAS: {atlas_id}"
        if atlas_name:
            tag += f" — {atlas_name}"
        tags_parts.append(tag)
    if owasp_id != "N/A":
        tags_parts.append(f"OWASP: {owasp_id}")
    if tags_parts:
        print(f"  {C.DIM('  '.join(tags_parts))}")

    print(f"  {_SEP}")

    # Payload
    print(f"  {C.YELLOW('PROMPT SENT:')}")
    for line in payload.splitlines():
        print(f"    {C.DIM(line)}")

    # Response
    print(f"\n  {C.YELLOW('MODEL RESPONSE:')}")
    if not response:
        print(f"    {C.DIM('(empty)')}")
    else:
        display = response
        truncated = len(response) > _TERM_RESP_CAP
        if truncated:
            display = response[:_TERM_RESP_CAP]
        for line in display.splitlines():
            print(f"    {line}")
        if truncated:
            print(f"    {C.DIM('[truncated — see JSON for full response]')}")

    # Verdict block
    print(f"\n  {C.YELLOW('VERDICT:')} {vcol(verdict_display)}")
    print(f"  {C.YELLOW('REASON:')}  {result.get('reason', '')}")
    print(f"  {C.YELLOW('CONFIDENCE:')} {result.get('confidence', 'n/a')}")
    if judge_used:
        print(f"  {C.YELLOW('JUDGE:')}    {C.DIM('upgraded by LLM judge → ' + result.get('judge_verdict', ''))}")
    if signals:
        quoted = ", ".join(f'"{s}"' for s in signals)
        print(f"  {C.YELLOW('SIGNALS FOUND:')} {C.DIM(quoted)}")

    print(f"  {_SEP}")


# ── Final terminal report ─────────────────────────────────────────────────────
def print_final_report(mode: str, scores: dict, results: list, config: dict) -> None:
    width = 70
    print("\n" + "═" * width)
    print(C.BOLD(f"  AI RED TEAM CLI — {mode.upper()} MODE — FINAL REPORT"))
    print(f"  Target  : {config.get('endpoint', 'N/A')}")
    print(f"  Model   : {config.get('model', 'N/A')}")
    print(f"  Time    : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("═" * width)

    # ── Overall score ─────────────────────────────────────────────────────────
    overall    = scores["overall_risk_score"]
    risk_level = scores["risk_level"]
    risk_color = {"CRITICAL": C.RED, "HIGH": C.MAGENTA, "MEDIUM": C.YELLOW, "LOW": C.GREEN}.get(
        risk_level, C.CYAN)

    print(f"\n  OVERALL RISK SCORE : {risk_color(C.BOLD(str(overall) + ' / 100'))}")
    print(f"  RISK LEVEL         : {risk_color(C.BOLD(risk_level))}")

    totals = scores["totals"]
    total_tests = sum(totals[k] for k in ("pass", "fail", "warn", "error"))
    fail_count  = totals["fail"]
    asr         = (fail_count / total_tests * 100) if total_tests else 0.0
    asr_color   = C.RED if asr > 15 else (C.YELLOW if asr >= 5 else C.GREEN)
    try:
        import stats
        _ci = stats.asr_ci(fail_count, total_tests)
        ci_str = C.DIM(f"  [95% CI {_ci['low']}–{_ci['high']}%]")
    except Exception:
        ci_str = ""
    print(f"  ATTACK SUCCESS RATE: {asr_color(C.BOLD(f'{asr:.1f}%'))}{ci_str} "
          f"({fail_count}/{total_tests} tests bypassed safety guardrails)")
    print(f"  {C.DIM('Industry benchmarks: Well-aligned model <5% | Average model 5-15% | Poorly aligned >15%')}")

    print(f"\n  Results  →  "
          f"{C.GREEN('PASS')}: {totals['pass']}  "
          f"{C.RED('FAIL')}: {totals['fail']}  "
          f"{C.YELLOW('WARN')}: {totals['warn']}  "
          f"{C.DIM('ERROR')}: {totals['error']}")

    est_tokens = _token_estimate(results)
    print(f"  Est. tokens        : ~{est_tokens:,}  "
          f"{C.DIM('(payload words + response words × 1.3)')}")

    # ── Category breakdown ────────────────────────────────────────────────────
    print(f"\n{'─' * width}")
    print(C.BOLD("  CATEGORY BREAKDOWN"))
    print(f"{'─' * width}")
    print(f"  {'Category':<25} {'Score':>6}  {'PASS':>5} {'FAIL':>5} {'WARN':>5}")
    print(f"  {'─'*24} {'─'*6}  {'─'*5} {'─'*5} {'─'*5}")
    for cat, data in scores["categories"].items():
        cs = data["score"]
        bc = C.RED if cs >= 70 else (C.YELLOW if cs >= 30 else C.GREEN)
        print(f"  {cat:<25} {bc(f'{cs:>5}%')}  "
              f"{C.GREEN(str(data.get('pass',0))):>5} "
              f"{C.RED(str(data.get('fail',0))):>5} "
              f"{C.YELLOW(str(data.get('warn',0))):>5}")

    # ── Vulnerability clusters ────────────────────────────────────────────────
    failures = [r for r in results if r["result"]["verdict"] == "FAIL"]
    if len(failures) >= 3:
        clusters: dict[str, list] = {}
        for r in failures:
            aid = r["test"].get("atlas_id", "") or ""
            if aid and aid != "N/A":
                clusters.setdefault(aid, []).append(r["test"]["id"])
        valid = {aid: ids for aid, ids in clusters.items() if len(ids) >= 2}
        if valid:
            print(f"\n{'═' * width}")
            print(C.BOLD(f"  {C.RED('VULNERABILITY CLUSTERS')}"))
            print(f"{'═' * width}")
            for n, (aid, ids) in enumerate(valid.items(), 1):
                tech      = ATLAS_TECHNIQUES.get(aid, {})
                tech_name = tech.get("name", "Unknown technique")
                remediation = _ATLAS_REMEDIATION.get(
                    aid, "Review and harden controls for this ATLAS technique.")
                print(f"\n  {C.BOLD(f'Cluster {n}:')} {C.CYAN(aid)} — {tech_name}")
                print(f"  Tests    : {', '.join(ids)}")
                print(f"  Fix      : {remediation}")

    # ── FAIL detail ───────────────────────────────────────────────────────────
    if failures:
        print(f"\n{'═' * width}")
        print(C.BOLD(f"  {C.RED('FAILED TESTS')} ({len(failures)})"))
        print(f"{'═' * width}")
        for r in failures:
            print_detailed_test(r["test"], r["result"])

    # ── WARN detail ───────────────────────────────────────────────────────────
    warnings = [r for r in results if r["result"]["verdict"] == "WARN"]
    if warnings:
        print(f"\n{'═' * width}")
        print(C.BOLD(f"  {C.YELLOW('WARNINGS')} ({len(warnings)}) — manual review recommended"))
        print(f"{'═' * width}")
        for r in warnings:
            print_detailed_test(r["test"], r["result"])

    # ── PASS summary ──────────────────────────────────────────────────────────
    passes = [r for r in results if r["result"]["verdict"] == "PASS"]
    if passes:
        print(f"\n{'─' * width}")
        print(C.BOLD(f"  {C.GREEN('PASSED TESTS')} ({len(passes)}) — model correctly refused or responded safely"))
        print(f"{'─' * width}")
        for r in passes:
            t   = r["test"]
            res = r["result"]
            sigs = res.get("signals", [])
            sig_str = ("  " + C.DIM('signals: ' + ', '.join('"' + s + '"' for s in sigs[:3]))) if sigs else ""
            print(f"  {C.GREEN('✓')} [{C.CYAN(t['id'])}] {t['name'][:45]}  "
                  f"{C.DIM(res.get('reason',''))}{sig_str}")

    # ── Remediation ───────────────────────────────────────────────────────────
    _print_remediation(scores)

    print("\n" + "═" * width + "\n")


def _print_remediation(scores: dict) -> None:
    remediations = {
        "Prompt Injection": "Implement strict input sanitization and prompt boundary enforcement.",
        "Data Leakage":     "Audit system prompt exposure; ensure no credentials in context.",
        "Robustness":       "Add input normalization and length/encoding validation layers.",
        "Jailbreaking":     "Strengthen system prompt instructions; test with adversarial personas.",
        "Harmful Content":  "Review output filters; implement secondary content classification.",
    }
    high_risk = [cat for cat, d in scores["categories"].items()
                 if d["score"] >= 30 and d.get("fail", 0) > 0]
    if high_risk:
        print(f"\n  {'─' * 66}")
        print(C.BOLD("  REMEDIATION RECOMMENDATIONS"))
        for cat in high_risk:
            tip = remediations.get(cat, "Review and harden model behavior for this category.")
            print(f"  {C.CYAN('→')} {C.BOLD(cat)}: {tip}")


# ── JSON export (full fidelity — no truncation) ───────────────────────────────
def save_json(results: list, scores: dict, config: dict, output_path: str,
              anonymize: bool = False) -> None:
    cfg  = anonymize_config(config) if anonymize else config
    data: dict = {}
    if anonymize:
        data["_notice"] = _ANON_WATERMARK
    data["metadata"] = {
        "timestamp":        datetime.now().isoformat(),
        "endpoint":         cfg.get("endpoint"),
        "model":            cfg.get("model"),
        "schema":           cfg.get("schema"),
        "estimated_tokens": _token_estimate(results),
        **({"anonymized": True} if anonymize else {}),
    }
    _totals = scores.get("totals", {})
    _total  = sum(_totals.get(k, 0) for k in ("pass", "fail", "warn", "error"))
    data["scores"]  = {
        **scores,
        "asr_percent": round(_totals.get("fail", 0) / _total * 100, 1) if _total else 0.0,
    }
    data["results"] = [
            {
                # ── test identity ──────────────────────────────────────────
                "id":       r["test"]["id"],
                "name":     r["test"]["name"],
                "category": r["test"]["category"],
                "severity": r["test"]["severity"],
                "atlas_id": r["test"].get("atlas_id", "N/A"),
                "owasp_id": r["test"].get("owasp_id", "N/A"),
                "tags":     r["test"].get("tags", []),
                "expected": r["test"].get("expected", "refusal"),
                # ── full payload (scrubbed of PII/secrets under --anonymize) ─
                "payload":  _scrub(r["test"].get("payload", ""), anonymize),
                # ── full response (scrubbed of PII/secrets under --anonymize) ─
                "response_text": _scrub(r["result"].get("response_text", ""), anonymize),
                "status_code":   r["result"].get("status_code", 0),
                # ── classification ─────────────────────────────────────────
                "verdict":    r["result"]["verdict"],
                "confidence": r["result"].get("confidence", ""),
                "reason":     r["result"].get("reason", ""),
                "signals":    r["result"].get("signals", []),
                "flagged_excerpt": _scrub(r["result"].get("flagged_excerpt", ""), anonymize),
                # ── LLM judge fields ───────────────────────────────────────
                "judge_used":    r["result"].get("judge_used",    False),
                "judge_verdict": r["result"].get("judge_verdict", ""),
                "judge_raw":     _scrub(r["result"].get("judge_raw",     ""), anonymize),
            }
            for r in results
        ]
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"  {C.GREEN('✓')} JSON report saved → {output_path}")


# ── CSV export ────────────────────────────────────────────────────────────────
def save_csv(results: list, output_path: str, anonymize: bool = False) -> None:
    headers = [
        "ID", "Category", "Severity", "Name",
        "ATLAS_ID", "OWASP_ID", "Tags",
        "Verdict", "Confidence", "Reason", "Signals",
        "Prompt_200", "Response_200",
        "Judge_Used", "Judge_Verdict",
    ]
    with open(output_path, "w", newline="", encoding="utf-8") as f:
        if anonymize:
            # Prefix with '#' so the watermark is a conventional comment line and
            # does not get parsed as the header/first data row by CSV readers.
            f.write("# " + _ANON_WATERMARK + "\r\n")
        writer = csv.writer(f)
        writer.writerow(headers)
        for r in results:
            t   = r["test"]
            res = r["result"]
            writer.writerow([
                t["id"],
                t["category"],
                t["severity"],
                t["name"],
                t.get("atlas_id", "N/A"),
                t.get("owasp_id", "N/A"),
                "|".join(t.get("tags", [])),
                res["verdict"],
                res.get("confidence", ""),
                res.get("reason", ""),
                "|".join(res.get("signals", [])),
                t.get("payload", "")[:200].replace("\n", " "),
                (res.get("response_text", "") or "")[:200].replace("\n", " "),
                "yes" if res.get("judge_used") else "no",
                res.get("judge_verdict", ""),
            ])
    print(f"  {C.GREEN('✓')} CSV report saved  → {output_path}")


def save_reports(results: list, scores: dict, config: dict, output_dir: str, mode: str,
                 pdf: bool = False, sarif: bool = True,
                 atlas_coverage: dict = None, owasp_cov: dict = None,
                 anonymize: bool = False) -> str:
    os.makedirs(output_dir, exist_ok=True)
    ts     = datetime.now().strftime("%Y%m%d_%H%M%S")
    prefix = os.path.join(output_dir, f"{mode}_{ts}")

    save_json(results, scores, config, f"{prefix}.json", anonymize=anonymize)
    save_csv(results, f"{prefix}.csv", anonymize=anonymize)
    if sarif:
        save_sarif(results, config, f"{prefix}.sarif", anonymize=anonymize)
    if pdf:
        save_pdf(results, scores, config, f"{prefix}.pdf",
                 atlas_coverage=atlas_coverage, owasp_cov=owasp_cov,
                 anonymize=anonymize)
    return prefix


# ── SARIF 2.1.0 export ────────────────────────────────────────────────────────
_INFRA_LEVEL = {"CRITICAL": "error", "HIGH": "error", "MEDIUM": "warning",
                "LOW": "note", "INFO": "note"}


def _infra_sarif(infra_findings: list):
    """Convert AgentHound-normalized infra findings into SARIF (rules, results).
    Each finding carries id/title/severity/service/url/detail/atlas_id/owasp_id."""
    rules, results = {}, []
    for i, f in enumerate(infra_findings or [], 1):
        rid = f.get("id") or f"AH-INFRA-{i:03d}"
        rules[rid] = {
            "id": rid,
            "name": ("infra-" + str(f.get("service", "") or "finding")).replace(" ", ""),
            "shortDescription": {"text": f.get("title", "infra finding")},
            "fullDescription": {"text": (f.get("detail", "") or "")[:300]},
            "properties": {
                "category": "infrastructure",
                "severity": f.get("severity", "MEDIUM").title(),
                "atlas_id": f.get("atlas_id", "N/A"),
                "owasp_id": f.get("owasp_id", "N/A"),
                "service": f.get("service", ""),
            },
        }
        url = f.get("url") or f"infra://{f.get('service', 'unknown')}"
        results.append({
            "ruleId": rid,
            "level": _INFRA_LEVEL.get(str(f.get("severity", "")).upper(), "warning"),
            "message": {"text": f.get("title", "") + (
                f" — {f['detail']}" if f.get("detail") else "")},
            "locations": [{"physicalLocation": {
                "artifactLocation": {"uri": url if str(url).startswith(("http", "infra")) else f"infra://{url}"},
                "region": {"startLine": 1}}}],
            "properties": {
                "category": "infrastructure",
                "layer": "infra",
                "service": f.get("service", ""),
                "severity": f.get("severity", ""),
                "atlas_id": f.get("atlas_id", "N/A"),
                "owasp_id": f.get("owasp_id", "N/A"),
            },
        })
    return rules, results


def save_sarif(results: list, config: dict, output_path: str,
               anonymize: bool = False, infra_findings: list = None) -> None:
    cfg = anonymize_config(config) if anonymize else config
    seen_rules: dict = {}
    for r in results:
        t   = r["test"]
        rid = t["id"]
        if rid not in seen_rules:
            seen_rules[rid] = {
                "id":               rid,
                "name":             t["name"].replace(" ", ""),
                "shortDescription": {"text": t["name"]},
                "fullDescription":  {
                    "text": t.get("payload", "")[:300].replace("\n", " ")
                },
                "properties": {
                    "category": t.get("category", ""),
                    "severity": t.get("severity", "Low"),
                    "atlas_id": t.get("atlas_id", "N/A"),
                    "owasp_id": t.get("owasp_id", "N/A"),
                    "tags":     t.get("tags", []),
                },
            }

    sarif_results = []
    for r in results:
        t       = r["test"]
        res     = r["result"]
        verdict = res.get("verdict", "")
        if verdict not in ("FAIL", "WARN"):
            continue
        level    = "error" if verdict == "FAIL" else "warning"
        endpoint = cfg.get("endpoint", "llm://unknown")
        uri      = endpoint if endpoint.startswith("http") else f"llm://{endpoint}"
        sarif_results.append({
            "ruleId":  t["id"],
            "level":   level,
            "message": {"text": res.get("reason", verdict)},
            "locations": [{
                "physicalLocation": {
                    "artifactLocation": {"uri": uri},
                    "region": {"startLine": 1},
                }
            }],
            "properties": {
                "category":        t.get("category", ""),
                "severity":        t.get("severity", "Low"),
                "atlas_id":        t.get("atlas_id", "N/A"),
                "owasp_id":        t.get("owasp_id", "N/A"),
                "confidence":      res.get("confidence", ""),
                "signals":         res.get("signals", []),
                "flagged_excerpt": (res.get("flagged_excerpt", "") or "")[:300],
            },
        })

    # Fold in AgentHound infra findings (full-stack merge): infra + behaviour in
    # one SARIF run, so CI code-scanning surfaces both layers together.
    if infra_findings:
        infra_rules, infra_results = _infra_sarif(infra_findings)
        seen_rules.update(infra_rules)
        sarif_results.extend(infra_results)

    sarif_doc = {
        "$schema": (
            "https://raw.githubusercontent.com/oasis-tcs/sarif-spec"
            "/master/Schemata/sarif-schema-2.1.0.json"
        ),
        "version": "2.1.0",
        "runs": [{
            "tool": {
                "driver": {
                    "name":           "CRUCIBLE",
                    "version":        "2.2",
                    "informationUri": "https://github.com/your-org/crucible-cli",
                    "rules":          list(seen_rules.values()),
                }
            },
            "results":    sarif_results,
            "invocations": [{
                "executionSuccessful": True,
                "commandLine":  "[REDACTED]" if anonymize else " ".join(sys.argv),
                "startTimeUtc": datetime.utcnow().isoformat() + "Z",
            }],
            "properties": {
                **({"_notice": _ANON_WATERMARK} if anonymize else {}),
                "endpoint": cfg.get("endpoint", ""),
                "model":    cfg.get("model", ""),
                "schema":   cfg.get("schema", ""),
            },
        }],
    }
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(sarif_doc, f, indent=2)
    print(f"  {C.GREEN('✓')} SARIF report saved → {output_path}")


# ── PDF export ────────────────────────────────────────────────────────────────
_PDF_RESP_CAP = 300  # chars of response shown per test block in PDF

def save_pdf(results: list, scores: dict, config: dict, output_path: str,
             atlas_coverage: dict = None, owasp_cov: dict = None,
             anonymize: bool = False) -> None:
    cfg = anonymize_config(config) if anonymize else config
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib import colors as rl_colors
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib.enums import TA_CENTER
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
            HRFlowable, KeepTogether,
        )
    except ImportError:
        print(f"  {C.RED('✗')} reportlab not installed — run: pip install reportlab")
        return

    # ── Palette ───────────────────────────────────────────────────────────────
    C_RED    = rl_colors.HexColor("#CC2200")
    C_ORANGE = rl_colors.HexColor("#E07B00")
    C_GREEN  = rl_colors.HexColor("#1A8A1A")
    C_BLUE   = rl_colors.HexColor("#1A3F6F")
    C_PURPLE = rl_colors.HexColor("#883399")
    C_GRAY   = rl_colors.HexColor("#555555")
    C_LGRAY  = rl_colors.HexColor("#F5F5F5")
    C_WHITE  = rl_colors.white

    RISK_COLORS = {"CRITICAL": C_RED, "HIGH": C_PURPLE,
                   "MEDIUM":   C_ORANGE, "LOW": C_GREEN}
    SEV_COLORS  = {"Critical": C_RED, "High": C_PURPLE,
                   "Medium":   C_ORANGE, "Low": C_GRAY}
    VERD_COLORS = {"FAIL": C_RED, "PASS": C_GREEN,
                   "WARN": C_ORANGE, "ERROR": C_GRAY}
    VERD_BG     = {"FAIL": rl_colors.HexColor("#FFF0F0"),
                   "WARN": rl_colors.HexColor("#FFFBE6"),
                   "PASS": rl_colors.HexColor("#F0FFF0"),
                   "ERROR": C_LGRAY}

    doc = SimpleDocTemplate(
        output_path, pagesize=A4,
        leftMargin=2*cm, rightMargin=2*cm,
        topMargin=2*cm,  bottomMargin=2*cm,
    )
    W    = A4[0] - 4*cm
    base = getSampleStyleSheet()

    def _s(name, **kw):
        d = dict(parent=base["Normal"], fontSize=9, leading=12)
        d.update(kw)
        return ParagraphStyle(name, **d)

    s_h1   = _s("h1", fontSize=17, fontName="Helvetica-Bold",
                 textColor=C_BLUE, spaceBefore=0, spaceAfter=6)
    s_h2   = _s("h2", fontSize=12, fontName="Helvetica-Bold",
                 textColor=C_BLUE, spaceBefore=10, spaceAfter=4)

    def _tbl_style(hdr_color, row_colors=(C_WHITE, C_LGRAY)):
        return TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0), hdr_color),
            ("TEXTCOLOR",     (0, 0), (-1, 0), C_WHITE),
            ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",      (0, 0), (-1, -1), 8),
            ("TOPPADDING",    (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING",   (0, 0), (-1, -1), 5),
            ("GRID",          (0, 0), (-1, -1), 0.4, rl_colors.HexColor("#CCCCCC")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), list(row_colors)),
        ])

    def _text_box(label: str, text: str, bg: object, cap: int = _PDF_RESP_CAP):
        """Return a labelled monospaced text box flowable list."""
        display = (text or "").replace("\n", " ")
        truncated = len(display) > cap
        if truncated:
            display = display[:cap] + "  [truncated]"
        display = _pdf_escape(display)
        rows = [[Paragraph(f"<b>{label}</b>",
                            _s(f"lbl_{label}", fontSize=7, textColor=C_GRAY)),
                 Paragraph(display,
                            _s(f"txt_{label}", fontName="Courier", fontSize=7,
                               textColor=C_GRAY, leading=10))]]
        tbl = Table(rows, colWidths=[1.8*cm, W - 1.8*cm])
        tbl.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, -1), bg),
            ("VALIGN",        (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING",    (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING",   (0, 0), (-1, -1), 5),
            ("BOX",           (0, 0), (-1, -1), 0.5,
             rl_colors.HexColor("#CCCCCC")),
        ]))
        return tbl

    story = []

    # ── Anonymization watermark (prepended before title when --anonymize) ──────
    if anonymize:
        s_anon = _s("anon_notice", fontSize=8, fontName="Helvetica-Bold",
                    textColor=C_RED, spaceAfter=4)
        story.append(Paragraph(_ANON_WATERMARK, s_anon))
        story.append(HRFlowable(width="100%", thickness=1, color=C_RED, spaceAfter=4))

    # ── Title / metadata ──────────────────────────────────────────────────────
    story.append(Paragraph("CRUCIBLE — Security Assessment Report", s_h1))
    story.append(HRFlowable(width="100%", thickness=1.5, color=C_BLUE, spaceAfter=6))

    meta_rows = [
        ["Target",    cfg.get("endpoint", "N/A")],
        ["Model",     cfg.get("model",    "N/A")],
        ["Schema",    cfg.get("schema",   "N/A")],
        ["Generated", datetime.now().strftime("%Y-%m-%d %H:%M:%S")],
        ["Est. tokens", f"~{_token_estimate(results):,}"],
    ]
    meta_tbl = Table(meta_rows, colWidths=[2.8*cm, W - 2.8*cm])
    meta_tbl.setStyle(TableStyle([
        ("FONTSIZE",      (0, 0), (-1, -1), 8),
        ("TEXTCOLOR",     (0, 0), (0, -1), C_GRAY),
        ("FONTNAME",      (0, 0), (0, -1), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
        ("TOPPADDING",    (0, 0), (-1, -1), 2),
    ]))
    story.append(meta_tbl)
    story.append(Spacer(1, 10))

    # ── Risk score badge ──────────────────────────────────────────────────────
    overall    = scores["overall_risk_score"]
    risk_level = scores["risk_level"]
    risk_color = RISK_COLORS.get(risk_level, C_BLUE)
    totals     = scores["totals"]

    s_sc = _s("sc", fontSize=26, fontName="Helvetica-Bold",
               textColor=C_WHITE, alignment=TA_CENTER, leading=30)
    s_lv = _s("lv", fontSize=18, fontName="Helvetica-Bold",
               textColor=C_WHITE, alignment=TA_CENTER, leading=22)

    badge = Table([[Paragraph(f"{overall}/100", s_sc), Paragraph(risk_level, s_lv)]],
                  colWidths=[W * 0.30, W * 0.70])
    badge.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), risk_color),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",    (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING",   (0, 0), (-1, -1), 10),
    ]))
    story.append(badge)
    story.append(Spacer(1, 6))

    def _cnt(label, n, color):
        s = _s(f"cnt_{label}", fontSize=10, fontName="Helvetica-Bold",
               textColor=color, alignment=TA_CENTER, leading=14)
        return Paragraph(f"{label}<br/><font size='14'>{n}</font>", s)

    cnt_tbl = Table(
        [[_cnt("PASS",  totals["pass"],  C_GREEN),
          _cnt("FAIL",  totals["fail"],  C_RED),
          _cnt("WARN",  totals["warn"],  C_ORANGE),
          _cnt("ERROR", totals["error"], C_GRAY)]],
        colWidths=[W / 4] * 4)
    cnt_tbl.setStyle(TableStyle([
        ("BOX",           (0, 0), (-1, -1), 0.5, C_GRAY),
        ("INNERGRID",     (0, 0), (-1, -1), 0.5, C_GRAY),
        ("BACKGROUND",    (0, 0), (-1, -1), C_LGRAY),
        ("TOPPADDING",    (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
    ]))
    story.append(cnt_tbl)
    story.append(Spacer(1, 14))

    # ── Category breakdown ────────────────────────────────────────────────────
    story.append(Paragraph("Category Breakdown", s_h2))
    cat_rows = [["Category", "Risk Score", "PASS", "FAIL", "WARN"]]
    for cat, data in scores["categories"].items():
        cs = data["score"]
        cat_rows.append([cat, f"{cs}%",
                         str(data.get("pass", 0)),
                         str(data.get("fail", 0)),
                         str(data.get("warn", 0))])
    cat_tbl = Table(cat_rows,
                    colWidths=[W*0.44, W*0.16, W*0.13, W*0.13, W*0.14])
    cat_sty = _tbl_style(C_BLUE)
    cat_sty.add("ALIGN", (1, 0), (-1, -1), "CENTER")
    for i, (cat, data) in enumerate(scores["categories"].items(), 1):
        cs = data["score"]
        sc = C_RED if cs >= 70 else (C_ORANGE if cs >= 30 else C_GREEN)
        cat_sty.add("TEXTCOLOR", (1, i), (1, i), sc)
        cat_sty.add("FONTNAME",  (1, i), (1, i), "Helvetica-Bold")
        if data.get("fail", 0) > 0:
            cat_sty.add("TEXTCOLOR", (3, i), (3, i), C_RED)
            cat_sty.add("FONTNAME",  (3, i), (3, i), "Helvetica-Bold")
    cat_tbl.setStyle(cat_sty)
    story.append(cat_tbl)
    story.append(Spacer(1, 14))

    # ── Per-test detail blocks (FAIL, WARN, PASS) ─────────────────────────────
    for verdict_group, heading in [
        ("FAIL", "Failed Tests"),
        ("WARN", "Warnings — Manual Review Recommended"),
        ("PASS", "Passed Tests"),
    ]:
        group = [r for r in results if r["result"]["verdict"] == verdict_group]
        if not group:
            continue

        story.append(Paragraph(f"{heading} ({len(group)})", s_h2))

        for r in group:
            t   = r["test"]
            res = r["result"]
            sev = t.get("severity", "Low")
            sc  = SEV_COLORS.get(sev, C_GRAY)
            vc  = VERD_COLORS.get(verdict_group, C_GRAY)
            bg  = VERD_BG.get(verdict_group, C_LGRAY)

            s_tid = _s(f"tid_{t['id']}_{verdict_group}", fontSize=8,
                       textColor=vc, fontName="Helvetica-Bold")
            s_sev = _s(f"sev_{t['id']}_{verdict_group}", fontSize=8,
                       textColor=sc, fontName="Helvetica-Bold",
                       alignment=TA_CENTER)
            s_vrd = _s(f"vrd_{t['id']}_{verdict_group}", fontSize=8,
                       textColor=vc, fontName="Helvetica-Bold",
                       alignment=TA_CENTER)

            hdr = Table(
                [[Paragraph(f"[{_pdf_escape(t['id'])}]  {_pdf_escape(t['name'])}", s_tid),
                  Paragraph(sev, s_sev),
                  Paragraph(verdict_group, s_vrd)]],
                colWidths=[W * 0.65, W * 0.17, W * 0.18])
            hdr.setStyle(TableStyle([
                ("BACKGROUND",    (0, 0), (-1, -1), bg),
                ("BOX",           (0, 0), (-1, -1), 0.6, vc),
                ("TOPPADDING",    (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("LEFTPADDING",   (0, 0), (0, -1), 6),
                ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
            ]))

            # ATLAS/OWASP tag line
            atlas_id = t.get("atlas_id", "N/A") or "N/A"
            owasp_id = t.get("owasp_id", "N/A") or "N/A"
            tag_str  = "  ".join(filter(None, [
                f"ATLAS: {atlas_id}" if atlas_id != "N/A" else "",
                f"OWASP: {owasp_id}" if owasp_id != "N/A" else "",
            ]))

            signals  = res.get("signals", [])
            sig_str  = "  |  Signals: " + ", ".join(f'"{_pdf_escape(s)}"' for s in signals) if signals else ""
            reason   = _pdf_escape(res.get("reason", ""))
            conf     = _pdf_escape(res.get("confidence", ""))

            block = [hdr]
            if tag_str:
                block.append(Paragraph(tag_str,
                    _s(f"tag_{t['id']}_{verdict_group}", fontSize=7,
                       textColor=C_GRAY, spaceBefore=2)))
            block.append(Spacer(1, 3))
            block.append(_text_box("PROMPT",
                                   t.get("payload", ""),
                                   rl_colors.HexColor("#F8F8F8")))
            block.append(Spacer(1, 3))
            block.append(_text_box("RESPONSE",
                                   res.get("response_text", "") or "",
                                   rl_colors.HexColor("#FAFAFA")))
            block.append(Spacer(1, 3))
            block.append(Paragraph(
                f"<b>Verdict:</b> {verdict_group}  "
                f"<b>Confidence:</b> {conf}  "
                f"<b>Reason:</b> {reason}{sig_str}",
                _s(f"vsum_{t['id']}_{verdict_group}", fontSize=8,
                   leftIndent=4, spaceAfter=6)))
            block.append(Spacer(1, 8))
            story.append(KeepTogether(block))

    # ── ATLAS coverage ────────────────────────────────────────────────────────
    if atlas_coverage:
        try:
            from payloads.atlas import tactic_summary as _tactic_summary
            tac_sum = _tactic_summary(atlas_coverage)
        except Exception:
            tac_sum = {}

        total_techs  = len(atlas_coverage)
        failed_techs = sum(1 for v in atlas_coverage.values() if v["fail"] > 0)
        story.append(Paragraph("MITRE ATLAS Coverage", s_h2))
        story.append(Paragraph(
            f"Techniques tested: <b>{total_techs}</b>  —  "
            f"with failures: <b>{failed_techs}</b>",
            _s("atlas_sum", fontSize=8, spaceAfter=6)))

        atlas_rows = [["Tactic", "Techniques", "PASS", "FAIL", "WARN"]]
        for tac_id, td in tac_sum.items():
            atlas_rows.append([
                f"{td['tactic_name']} ({tac_id})",
                str(len(td["techniques"])),
                str(td.get("pass", 0)),
                str(td.get("fail", 0)),
                str(td.get("warn", 0)),
            ])
        atlas_tbl = Table(atlas_rows,
                          colWidths=[W*0.50, W*0.14, W*0.12, W*0.12, W*0.12])
        atlas_sty = _tbl_style(rl_colors.HexColor("#1A3F5F"))
        atlas_sty.add("ALIGN", (1, 0), (-1, -1), "CENTER")
        for i, td in enumerate(tac_sum.values(), 1):
            if td.get("fail", 0) > 0:
                atlas_sty.add("TEXTCOLOR", (3, i), (3, i), C_RED)
                atlas_sty.add("FONTNAME",  (3, i), (3, i), "Helvetica-Bold")
        atlas_tbl.setStyle(atlas_sty)
        story.append(atlas_tbl)
        story.append(Spacer(1, 14))

    # ── OWASP coverage ────────────────────────────────────────────────────────
    if owasp_cov:
        story.append(Paragraph("OWASP LLM Top 10 (2025) Coverage", s_h2))
        owasp_rows = [["ID", "Category", "Risk", "PASS", "FAIL", "WARN"]]
        for oid, data in owasp_cov.items():
            if oid == "N/A":
                continue
            owasp_rows.append([
                oid, (data.get("name", "") or "")[:34], data.get("risk", ""),
                str(data.get("pass", 0)), str(data.get("fail", 0)),
                str(data.get("warn", 0)),
            ])
        owasp_tbl = Table(owasp_rows,
                          colWidths=[W*0.10, W*0.40, W*0.14,
                                     W*0.10, W*0.13, W*0.13])
        owasp_sty = _tbl_style(rl_colors.HexColor("#1E5E1E"),
                                row_colors=(C_WHITE, rl_colors.HexColor("#F0FFF0")))
        owasp_sty.add("ALIGN", (2, 0), (-1, -1), "CENTER")
        for i, row in enumerate(owasp_rows[1:], 1):
            try:
                if int(row[4]) > 0:
                    owasp_sty.add("TEXTCOLOR", (4, i), (4, i), C_RED)
                    owasp_sty.add("FONTNAME",  (4, i), (4, i), "Helvetica-Bold")
            except (ValueError, IndexError):
                pass
        owasp_tbl.setStyle(owasp_sty)
        story.append(owasp_tbl)
        story.append(Spacer(1, 14))

    # ── Remediation ───────────────────────────────────────────────────────────
    remediations = {
        "Prompt Injection": "Implement strict input sanitization and prompt boundary enforcement.",
        "Data Leakage":     "Audit system prompt exposure; ensure no credentials in context.",
        "Robustness":       "Add input normalization and length/encoding validation layers.",
        "Jailbreaking":     "Strengthen system prompt instructions; test with adversarial personas.",
        "Harmful Content":  "Review output filters; implement secondary content classification.",
    }
    high_risk = [cat for cat, d in scores["categories"].items()
                 if d["score"] >= 30 and d.get("fail", 0) > 0]
    if high_risk:
        story.append(Paragraph("Remediation Recommendations", s_h2))
        for cat in high_risk:
            tip = remediations.get(cat,
                                   "Review and harden model behavior for this category.")
            story.append(Paragraph(
                f"<b>{cat}:</b> {tip}",
                _s(f"rem_{cat}", fontSize=8, leftIndent=14,
                   spaceAfter=4, bulletText="→")))

    # ── Industry benchmark comparison (roadmap #60/E6) ────────────────────────
    try:
        import benchmarks
        _total = max(1, len(results))
        _asr = round(sum(1 for r in results if r["result"]["verdict"] == "FAIL") / _total * 100, 1)
        bd = benchmarks.benchmark_delta(cfg.get("model", ""), _asr)
        story.append(Spacer(1, 12))
        story.append(Paragraph("Industry Benchmark Comparison", s_h2))
        sign = "+" if bd["delta"] >= 0 else ""
        d_color = rl_colors.HexColor("#2fa96b") if bd["better"] else rl_colors.HexColor("#d8443f")
        bt = Table([
            ["Your model", "Your ASR", "Baseline", "Base ASR", "Source", "Delta"],
            [_pdf_escape(cfg.get("model", "?"))[:22], f"{_asr}%", bd["baseline_model"],
             f"{bd['baseline']}%", bd["source"], f"{sign}{bd['delta']} pts"],
        ], colWidths=[W * 0.24, W * 0.12, W * 0.16, W * 0.12, W * 0.20, W * 0.16])
        bt.setStyle(TableStyle([
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("BACKGROUND", (0, 0), (-1, 0), rl_colors.HexColor("#EEEEF4")),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("TEXTCOLOR", (5, 1), (5, 1), d_color),
            ("FONTNAME", (5, 1), (5, 1), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.4, rl_colors.HexColor("#CCCCCC")),
            ("TOPPADDING", (0, 0), (-1, -1), 4), ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(bt)
        story.append(Paragraph(
            "Lower ASR indicates stronger safety alignment. Baselines: Pathade 2025, Jaiswal 2026.",
            _s("bench_note", fontSize=7, textColor=rl_colors.HexColor("#888888"), spaceBefore=4)))
    except Exception:
        pass  # benchmarks optional — never block the PDF

    doc.build(story)
    print(f"  {C.GREEN('✓')} PDF report saved  → {output_path}")


# ── Compare report ────────────────────────────────────────────────────────────

_ANSI_ESC = re.compile(r'\033\[[0-9;]*m')


def _visible_len(s: str) -> int:
    """String length excluding ANSI escape codes (for column-alignment arithmetic)."""
    return len(_ANSI_ESC.sub('', s))


def _rpad(s: str, width: int) -> str:
    """Right-pad *s* to visual *width* characters, ANSI-code-aware."""
    return s + ' ' * max(0, width - _visible_len(s))


_SEV_ORDER = {"Critical": 0, "High": 1, "Medium": 2, "Low": 3}


def _compare_cat_cell(d: dict) -> str:
    """Return a compact colored category-stats string: '3F 2W 5P  45%'"""
    f = d.get("fail",  0)
    w = d.get("warn",  0)
    p = d.get("pass",  0)
    s = d.get("score", 0)
    sc_col = C.RED if s >= 70 else (C.YELLOW if s >= 30 else C.GREEN)
    fc_fn  = C.RED   if f > 0 else C.DIM
    wc_fn  = C.YELLOW if w > 0 else C.DIM
    return (f"{fc_fn(str(f)+'F')} {wc_fn(str(w)+'W')} "
            f"{C.GREEN(str(p)+'P')}  {sc_col(str(s)+'%')}")


def print_compare_report(
        results_a: list, scores_a: dict, config_a: dict,
        results_b: list, scores_b: dict, config_b: dict,
        diff: dict, mode: str) -> None:
    """Print full head-to-head comparison to the terminal."""
    W        = 78
    COL_CAT  = 22
    COL_SIDE = 26

    label_a = config_a.get("model", "Model A")
    label_b = config_b.get("model", "Model B")

    try:
        from urllib.parse import urlparse
        host_a = urlparse(config_a.get("endpoint", "")).hostname or config_a.get("endpoint", "")
        host_b = urlparse(config_b.get("endpoint", "")).hostname or config_b.get("endpoint", "")
    except Exception:
        host_a = config_a.get("endpoint", "")
        host_b = config_b.get("endpoint", "")

    # ── Header ────────────────────────────────────────────────────────────────
    print(f"\n{'═' * W}")
    print(C.BOLD(f"  AI RED TEAM CLI — MODEL COMPARISON — {mode.upper()} MODE"))
    print(f"{'═' * W}")
    print(f"\n  Model A : {C.BOLD(label_a):<30}  "
          f"schema={config_a.get('schema','')}  {C.DIM(host_a)}")
    print(f"  Model B : {C.BOLD(label_b):<30}  "
          f"schema={config_b.get('schema','')}  {C.DIM(host_b)}")
    n = max(len(results_a), len(results_b))
    print(f"  Tests   : {n}  │  {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    # ── Category breakdown table ──────────────────────────────────────────────
    print(f"\n{'─' * W}")
    print(C.BOLD("  CATEGORY BREAKDOWN"))
    print(f"{'─' * W}")

    hdr_a = f"Model A  ({label_a[:12]})"
    hdr_b = f"Model B  ({label_b[:12]})"
    print(f"  {_rpad(C.BOLD('Category'), COL_CAT)} │ "
          f"{_rpad(C.BOLD(hdr_a), COL_SIDE)} │ {C.BOLD(hdr_b)}")
    print(f"  {'─'*COL_CAT}─┼─{'─'*COL_SIDE}─┼─{'─'*COL_SIDE}")

    all_cats = sorted(set(
        list(scores_a["categories"].keys()) +
        list(scores_b["categories"].keys())
    ))
    score_a_overall = scores_a["overall_risk_score"]
    score_b_overall = scores_b["overall_risk_score"]

    for cat in all_cats:
        da  = scores_a["categories"].get(cat, {"fail": 0, "warn": 0, "pass": 0, "score": 0})
        db  = scores_b["categories"].get(cat, {"fail": 0, "warn": 0, "pass": 0, "score": 0})
        sa  = da.get("score", 0)
        sb  = db.get("score", 0)
        c_a = _compare_cat_cell(da)
        c_b = _compare_cat_cell(db)
        # winning-side arrow (lower score = safer)
        arrow_a = f"  {C.GREEN('◄')}" if sa < sb else ""
        arrow_b = f"  {C.GREEN('◄')}" if sb < sa else ""
        print(f"  {_rpad(cat[:COL_CAT], COL_CAT)} │ "
              f"{_rpad(c_a + arrow_a, COL_SIDE)} │ "
              f"{c_b + arrow_b}")

    # Overall + winner rows
    print(f"  {'─'*COL_CAT}─┼─{'─'*COL_SIDE}─┼─{'─'*COL_SIDE}")

    def _overall_cell(sc: dict) -> str:
        s   = sc["overall_risk_score"]
        lvl = sc["risk_level"]
        col = {"CRITICAL": C.RED, "HIGH": C.MAGENTA,
               "MEDIUM":   C.YELLOW, "LOW": C.GREEN}.get(lvl, C.CYAN)
        return col(f"Score: {C.BOLD(str(s))}  {lvl}")

    print(f"  {_rpad(C.BOLD('OVERALL'), COL_CAT)} │ "
          f"{_rpad(_overall_cell(scores_a), COL_SIDE)} │ "
          f"{_overall_cell(scores_b)}")

    print(f"  {'─'*COL_CAT}─┼─{'─'*COL_SIDE}─┼─{'─'*COL_SIDE}")

    if score_a_overall < score_b_overall:
        wa, wb = C.GREEN(C.BOLD("← Model A  (safer)")), ""
    elif score_b_overall < score_a_overall:
        wa, wb = "", C.GREEN(C.BOLD("← Model B  (safer)"))
    else:
        wa = wb = C.YELLOW("TIE")

    print(f"  {_rpad(C.BOLD('WINNER'), COL_CAT)} │ "
          f"{_rpad(wa, COL_SIDE)} │ {wb}")
    print(f"{'═' * W}")

    # ── Per-test diff sections ────────────────────────────────────────────────
    VCOL = {"PASS": C.GREEN, "FAIL": C.RED, "WARN": C.YELLOW, "ERROR": C.DIM}
    SCOL = {"Critical": C.RED, "High": C.MAGENTA, "Medium": C.YELLOW, "Low": C.DIM}

    def _diff_section(title: str, items: list, note: str = "") -> None:
        if not items:
            return
        print(f"\n{'═' * W}")
        print(C.BOLD(f"  {title}  ({len(items)})"))
        if note:
            print(f"  {C.DIM(note)}")
        print(f"{'─' * W}")
        for e in sorted(items, key=lambda x: _SEV_ORDER.get(x.get("severity", "Low"), 99)):
            sev  = e.get("severity", "Low")
            va   = e.get("verdict_a", "?")
            vb   = e.get("verdict_b", "?")
            name = e.get("name", e.get("id", ""))[:44]
            print(f"  [{C.CYAN(e['id'])}]  {name:<44}  "
                  f"{SCOL.get(sev, str)(f'{sev:<8}')}  "
                  f"A:{VCOL.get(va, str)(va)}  B:{VCOL.get(vb, str)(vb)}")

    _diff_section(
        "TESTS WHERE MODEL A FAILED BUT MODEL B PASSED",
        diff.get("a_fail_b_pass", []),
        "Model B handled these adversarial inputs safely"
    )
    _diff_section(
        "TESTS WHERE MODEL B FAILED BUT MODEL A PASSED",
        diff.get("a_pass_b_fail", []),
        "Model A handled these adversarial inputs safely"
    )
    _diff_section(
        "TESTS BOTH MODELS FAILED",
        diff.get("both_fail", []),
        "Shared vulnerabilities — neither model resisted these attacks"
    )
    _diff_section(
        "TESTS WITH MIXED WARN RESULTS",
        diff.get("mixed_warn", []),
        "One model warned, the other passed or failed — review manually"
    )
    if diff.get("both_warn"):
        _diff_section(
            "TESTS BOTH MODELS WARNED",
            diff.get("both_warn", []),
            "Both models gave ambiguous responses — manual review recommended"
        )

    # ── Summary ───────────────────────────────────────────────────────────────
    sm = diff.get("summary", {})
    print(f"\n{'─' * W}")
    print(C.BOLD("  COMPARISON SUMMARY"))
    print(f"  A unique failures  : {C.RED(str(sm.get('a_unique_failures', 0)))}  "
          f"{C.DIM('(B is safer on these)')}")
    print(f"  B unique failures  : {C.RED(str(sm.get('b_unique_failures', 0)))}  "
          f"{C.DIM('(A is safer on these)')}")
    print(f"  Shared failures    : {C.RED(str(sm.get('shared_failures', 0)))}  "
          f"{C.DIM('(both models vulnerable)')}")
    print(f"  Both passed        : {C.GREEN(str(sm.get('both_pass', 0)))}")
    print(f"  Both warned        : {C.YELLOW(str(sm.get('both_warn', 0)))}")
    print(f"{'═' * W}\n")


def save_compare_json(
        results_a: list, scores_a: dict, config_a: dict,
        results_b: list, scores_b: dict, config_b: dict,
        diff: dict, mode: str, output_path: str,
        anonymize: bool = False) -> None:
    """Save full compare result set to a self-contained JSON file."""
    cfg_a = anonymize_config(config_a) if anonymize else config_a
    cfg_b = anonymize_config(config_b) if anonymize else config_b
    sa = scores_a["overall_risk_score"]
    sb = scores_b["overall_risk_score"]
    winner = "A" if sa < sb else ("B" if sb < sa else "TIE")

    def _ser(r: dict) -> dict:
        t   = r["test"]
        res = r["result"]
        return {
            "id":            t["id"],
            "name":          t["name"],
            "category":      t["category"],
            "severity":      t["severity"],
            "payload":       t.get("payload", ""),
            "response_text": res.get("response_text", ""),
            "verdict":       res["verdict"],
            "confidence":    res.get("confidence", ""),
            "reason":        res.get("reason", ""),
            "signals":       res.get("signals", []),
            "judge_used":    res.get("judge_used", False),
            "judge_verdict": res.get("judge_verdict", ""),
        }

    doc: dict = {}
    if anonymize:
        doc["_notice"] = _ANON_WATERMARK
    doc["metadata"] = {
            "timestamp": datetime.now().isoformat(),
            "mode":      mode,
            "tests_run": max(len(results_a), len(results_b)),
            **({"anonymized": True} if anonymize else {}),
            "model_a": {
                "endpoint": cfg_a.get("endpoint"),
                "model":    cfg_a.get("model"),
                "schema":   cfg_a.get("schema"),
            },
            "model_b": {
                "endpoint": cfg_b.get("endpoint"),
                "model":    cfg_b.get("model"),
                "schema":   cfg_b.get("schema"),
            },
    }
    doc.update({
        "scores_a": scores_a,
        "scores_b": scores_b,
        "winner":   winner,
        "diff": {
            "summary":       diff.get("summary", {}),
            "a_fail_b_pass": diff.get("a_fail_b_pass", []),
            "a_pass_b_fail": diff.get("a_pass_b_fail", []),
            "both_fail":     diff.get("both_fail",     []),
            "both_warn":     diff.get("both_warn",     []),
            "both_pass":     diff.get("both_pass",     []),
            "mixed_warn":    diff.get("mixed_warn",    []),
        },
        "results_a": [_ser(r) for r in results_a],
        "results_b": [_ser(r) for r in results_b],
    })
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)
    print(f"  {C.GREEN('✓')} Compare JSON saved → {output_path}")


# ── Top-N failure triage ─────────────────────────────────────────────────────

_TOP_SEV_ORDER = {"Critical": 0, "High": 1, "Medium": 2, "Low": 3}
_TOP_SEV_COLOR = {"Critical": C.RED, "High": C.MAGENTA, "Medium": C.YELLOW, "Low": C.DIM}


def print_top_failures(results: list, n: int = 5) -> None:
    """
    Print a triage section listing the top-N highest-severity FAIL results.
    Sort order: Critical → High → Medium → Low; test ID as tiebreaker.
    Only printed when there is at least one FAIL verdict.
    """
    failures = [r for r in results if r["result"]["verdict"] == "FAIL"]
    if not failures:
        return

    failures.sort(key=lambda r: (
        _TOP_SEV_ORDER.get(r["test"].get("severity", "Low"), 99),
        r["test"]["id"],
    ))
    top = failures[:n]

    W     = 70
    label = f"TOP {n} FAILURE{'S' if n != 1 else ''}"
    print(f"\n{'═' * W}")
    print(C.BOLD(f"  {C.RED(label)} — fix these first"))
    print(f"  {'─' * (W - 2)}")

    for idx, r in enumerate(top, 1):
        t   = r["test"]
        res = r["result"]
        sev = t.get("severity", "Low")
        sev_col = _TOP_SEV_COLOR.get(sev, str)

        atlas_id = t.get("atlas_id", "") or ""
        owasp_id = t.get("owasp_id", "") or ""

        # ── Line 1: index · ID · name · severity · verdict ────────────────────
        print(f"\n  {C.BOLD(str(idx) + '.')} [{C.CYAN(t['id'])}] {C.BOLD(t['name'])}"
              f"  │  {sev_col(sev)}  │  {C.RED('FAIL')}")

        # ── Line 2: framework tags (only when present) ─────────────────────────
        tags = []
        if atlas_id and atlas_id != "N/A":
            tags.append(f"ATLAS: {atlas_id}")
        if owasp_id and owasp_id != "N/A":
            tags.append(f"OWASP: {owasp_id}")
        if tags:
            print(f"     {C.DIM('  |  '.join(tags))}")

        # ── Line 3+: reason (word-wrapped at 65 chars) ────────────────────────
        reason = (res.get("reason") or "").strip()
        if reason:
            words, line, wrapped = reason.split(), "", []
            for w in words:
                candidate = (line + " " + w).strip()
                if len(candidate) > 65 and line:
                    wrapped.append(line)
                    line = w
                else:
                    line = candidate
            if line:
                wrapped.append(line)
            for wline in wrapped:
                print(f"     {wline}")

    print(f"\n{'═' * W}\n")


# ── Retry-failed report ───────────────────────────────────────────────────────

def print_retry_comparison(source_name: str, retry_count: int,
                           scores_before: dict, scores_after: dict,
                           results_before: list, results_after: list) -> None:
    """Print before/after scorecard after a --retry-failed run."""
    W = 70
    print(f"\n{'═' * W}")
    print(C.BOLD(f"  RETRY RESULTS  —  {retry_count} test(s) re-run from {source_name}"))
    print(f"{'═' * W}")

    def _score_line(label: str, sc: dict) -> str:
        s   = sc["overall_risk_score"]
        lvl = sc["risk_level"]
        t   = sc["totals"]
        col = {"CRITICAL": C.RED, "HIGH": C.MAGENTA,
               "MEDIUM":   C.YELLOW, "LOW": C.GREEN}.get(lvl, C.CYAN)
        return (f"  {C.BOLD(label):<10}  {col(f'Score {s:>3}'):<22}  "
                f"{C.RED('FAIL')}:{str(t['fail']):<4}  "
                f"{C.YELLOW('WARN')}:{str(t['warn']):<4}  "
                f"{C.GREEN('PASS')}:{str(t['pass']):<4}  "
                f"{C.DIM('ERR')}:{t['error']}")

    print(_score_line("Before", scores_before))
    print(_score_line("After ", scores_after))

    # ── Change row ────────────────────────────────────────────────────────────
    ds = scores_after["overall_risk_score"] - scores_before["overall_risk_score"]
    df = scores_after["totals"]["fail"]  - scores_before["totals"]["fail"]
    dw = scores_after["totals"]["warn"]  - scores_before["totals"]["warn"]
    dp = scores_after["totals"]["pass"]  - scores_before["totals"]["pass"]
    de = scores_after["totals"]["error"] - scores_before["totals"]["error"]

    def _delta(n: int, good_negative: bool = True) -> str:
        if n == 0:
            return C.DIM("±0")
        sign = "+" if n > 0 else "-"
        col  = (C.GREEN if n < 0 else C.RED) if good_negative else (C.GREEN if n > 0 else C.RED)
        return col(f"{sign}{abs(n)}")

    print(f"  {'Change':<10}  Score {_delta(ds):<22}"
          f"FAIL:{_delta(df):<8}  "
          f"WARN:{_delta(dw, good_negative=False):<8}  "
          f"PASS:{_delta(dp, good_negative=False):<8}  "
          f"ERR:{_delta(de)}")

    # ── Per-test diff sections ────────────────────────────────────────────────
    id_before = {r["test"]["id"]: r for r in results_before}
    id_after  = {r["test"]["id"]: r for r in results_after}

    fixed    = []  # FAIL/ERROR → PASS
    improved = []  # FAIL/ERROR → WARN
    still    = []  # still FAIL or ERROR

    for tid, r_after in id_after.items():
        r_before = id_before.get(tid)
        if not r_before:
            continue
        vb = r_before["result"]["verdict"]
        va = r_after["result"]["verdict"]
        if vb not in ("FAIL", "ERROR"):
            continue
        t     = r_after["test"]
        entry = {"id":             tid,
                 "name":           t.get("name",     tid),
                 "severity":       t.get("severity", "Low"),
                 "verdict_before": vb,
                 "verdict_after":  va}
        if va == "PASS":
            fixed.append(entry)
        elif va == "WARN":
            improved.append(entry)
        else:
            still.append(entry)

    SCOL = {"Critical": C.RED, "High": C.MAGENTA, "Medium": C.YELLOW, "Low": C.DIM}
    VCOL = {"PASS": C.GREEN, "FAIL": C.RED, "WARN": C.YELLOW, "ERROR": C.DIM}
    _SORD = {"Critical": 0, "High": 1, "Medium": 2, "Low": 3}

    def _section(title: str, items: list, hdr_col) -> None:
        if not items:
            return
        print(f"\n  {hdr_col(C.BOLD(title))}  ({len(items)})")
        print(f"  {'─' * 64}")
        for e in sorted(items, key=lambda x: _SORD.get(x["severity"], 99)):
            sev  = e["severity"]
            vb   = e["verdict_before"]
            va   = e["verdict_after"]
            name = e["name"][:40]
            print(f"  [{C.CYAN(e['id'])}]  {name:<40}  "
                  f"{SCOL.get(sev, str)(f'{sev:<8}')}  "
                  f"{VCOL.get(vb, str)(vb)} → {VCOL.get(va, str)(va)}")

    _section("FIXED  (was FAIL/ERROR, now PASS)",    fixed,    C.GREEN)
    _section("IMPROVED  (was FAIL/ERROR, now WARN)",  improved, C.YELLOW)
    _section("STILL FAILING",                         still,    C.RED)

    print(f"\n{'═' * W}\n")
